name: Illyrion's CI/CD
run-name: "Illyrion's CI/CD"

on:
  push:
    branches: [main]
    paths: ["illyriarpg/**"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-server:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '.deploy')
    environment:
      name: ${{ github.ref_name }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: sync_files
        name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./illyriarpg/
          server-dir: /
